### PR TITLE
generate: Add validation for TFState version

### LINKED ISSUE #72: Limit State v4
The current implementation only works with TF version 4 as the migration from TFState V3->v4 do not carry the `depends_on` so we cannot create the dependencies between Nodes.

For more info on v3->v4 https://github.com/hashicorp/terraform/issues/27020.

### PR DESCRIPTION
**Pull request by xescugc**
As we only support the v4 for now

Close #72

### CODE REVIEW

**Review by xlr-8 — CHANGES_REQUESTED** [review]
What does version 4 corresponds to? This should be more properly documented for users, to highlight which is the lowest terraform version we support. It would also be nice to open that topic of supporting multiple (and mostly older) versions of terraform too.

**Comment by xescugc** [comment]
Version 4 is TF 0.12.

I thought I did modify the README, I'll.

I'll also open another Issue to try to find a way around it, somehow. This only affects the State but not HCL.

**Comment by xescugc** [comment]
Added it to the Readme

**Comment by xescugc** [comment]
> Regarding how far back we want to go, that's up to us to decide with what we feel comfortable/mostly used.
Supporting the one terraform support would be (perhaps too much to start but) great for example, while supporting only one version would be way too restricting.

Yeh with the #74 the idea would be to have have V4 and V3. IDK how V1 or V2 are but they feel too old potentially.

**Review by xlr-8 — APPROVED** [review]

**Pull request merged**
